# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    runSettingsFile: Source/Icebreaker.Tests/test.runsettings
    codeCoverageEnabled: true

- task: RoslynAnalyzers@2
  inputs:
    userProvideBuildInfo: 'auto'

- task: PoliCheck@1
  inputs:
    inputType: 'Basic'
    targetType: 'F'
    targetArgument: '$(Build.SourcesDirectory)'
    result: 'PoliCheck.xml'

- task: SdtReport@1
  inputs:
    AllTools: false
    APIScan: true
    BinSkim: true
    BinSkimBreakOn: 'Error'
    CodesignValidation: true
    CodesignValidationBreakOn: 'Error'
    CredScan: true
    FortifySCA: false
    FxCop: true
    FxCopBreakOn: 'ErrorAbove'
    ModernCop: true
    ModernCopBreakOn: 'Error'
    MSRD: true
    PoliCheck: true
    PoliCheckBreakOn: 'Severity1'
    RoslynAnalyzers: true
    RoslynAnalyzersBreakOn: 'Error'
    SDLNativeRules: true
    Semmle: true
    SemmleBreakOn: 'Error'
    TSLint: false
    ToolLogsNotFoundAction: 'Standard'

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'

- task: PublishSecurityAnalysisLogs@2
  inputs:
    ArtifactName: 'CodeAnalysisLogs'
    ArtifactType: 'Container'
    AllTools: false
    AntiMalware: true
    APIScan: true
    BinSkim: true
    CodesignValidation: true
    CredScan: true
    FortifySCA: false
    FxCop: true
    ModernCop: true
    MSRD: true
    PoliCheck: true
    RoslynAnalyzers: true
    SDLNativeRules: true
    Semmle: true
    TSLint: true
    WebScout: false
    ToolLogsNotFoundAction: 'Standard'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'